---
- name: "Installing and Managing Apache on webserver"
  become: true
  hosts: amazon
  vars_files:
    - variables.yml
  tasks:

    - name: "Installing Apache Webserver Package"
      yum:
        name: httpd
        state: present


    - name: "Apache - Enabling php Support"
      shell: amazon-linux-extras install php7.4 -y


    - name: "Webserver - Creating httpd.conf file"
      template:
        src: ./httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf 
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"


    - name: "Webserver - Service restart/enable"
      service:
        name: httpd
        state: restarted
        enabled: true
    
    - name: "Webserver - Creating VirtualHost {{ httpd_domain }}"
      template:
        src: "./virtualhost.conf.j2"
        dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}" 
        
        
    - name: "Webserver - Creating DocumentRoot /var/www/html/{{ httpd_domain }}"
      file:
        path: "/var/www/html/{{ httpd_domain }}"
        state: directory
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      
    - name: "Apache - Creating Sample test.php & test.html"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ httpd_domain }}/"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
      with_items:
        - test.html
        - test.php

    - name: "Webserver - Service restart/enable"
      service:
        name: httpd
        state: restarted
        enabled: true

    - name: "Mariadb Package Installation"
      yum:
        name:
          - mariadb-server
          - MySQL-python
        state: present

    - name: "Mariadb-server restarting/enabling service"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "Mariadb-server - root password update"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        name: "root"
        password: "{{ mariadb_root_password }}"
        host_all: true

    - name: "Mariadb-server -removing anonymous users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: ""
        password: ""
        host_all: true
        state: absent

    - name: "creating  database {{ mariadb_extra_database }}"
      mysql_db:
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ mariadb_extra_database }}"
        state: present
  
    - name: "creating extra user {{ mariadb_extra_user }}"
      mysql_user:
        login_user: "root"
        login_password: "{{ mariadb_root_password }}"
        name: "{{ mariadb_extra_user }}"
        password: "{{ mariadb_extra_password }}"
        state: present
        host: "%"
        priv: "{{ mariadb_extra_database }}.*:ALL"

    - name: "Wordpress downloading archive file {{ wp_url }}"
      get_url:
        url: "{{ wp_url }}"
        dest: "/tmp/wordpress.tar.gz"

    - name: "Wordpress extracting Wordpress archive /tmp/wordpress.tar.gz"
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/tmp"
        remote_src: true
      
